// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;

namespace SharpSDL
{
    public unsafe partial class SDLPlatform
    {
        public partial struct __Internal
        {
            [SuppressUnmanagedCodeSecurity]
            [DllImport("SDL2", CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl,
                EntryPoint="SDL_GetPlatform")]
            internal static extern global::System.IntPtr GetPlatform();
        }

        /// <summary>Gets the name of the platform.</summary>
        public static string GetPlatform()
        {
            var __ret = __Internal.GetPlatform();
            return Marshal.PtrToStringAnsi(__ret);
        }
    }
}
